module.exports = {
  City: [
    {id: 1, name: 'Cravinhos'},
    {id: 2, name: 'Serrana'},
  ],
  Serrana: [
    {id: 1, name: 'Rua Venerando Garcia da Costa'},
    {id: 2, name: 'Rua Adão Adolfo'},
    {id: 3, name: 'Rua Severino José do Vale'},
    {id: 4, name: 'Rua Luiz Siodoni'},
    {id: 5, name: 'Rua Adolfo Bertolini'},
    {id: 6, name: 'Rua Moacir Bertagnoli'},
    {id: 7, name: 'Rua Antônio Selegato'},
    {id: 8, name: 'Rua Sebastião F. do Nascimento'},
    {id: 9, name: 'Rua Antônio Moura'},
    {id: 10, name: 'Rua Nelson Garavazzo'},
    {id: 11, name: 'Rua Nelson Selegato'},
    {id: 12, name: 'Rua Nagib M. Issa'},
    {id: 13, name: 'Rua Dário José Rodrigues'},
    {id: 14, name: 'Rua Benedito Coutinho de Mattos'},
    {id: 15, name: 'Rua Flávio José do Vale'},
    {id: 16, name: 'Rua Basilino J. Do Valle'},
    {id: 17, name: 'Rua Miguel Coimbra'},
    {id: 18, name: 'Rua Serafim do Bem'},
    {id: 19, name: 'Rua Nossa Senhora das Dores'},
    {id: 20, name: 'Rua Barão do Rio Branco'},
    {id: 21, name: 'Rua Adão Adolfo'},
    {id: 22, name: 'Rua Severino José do Vale'},
    {id: 23, name: 'Rua Francelino Reis'},
    {id: 24, name: 'Rua Sebastião Tercário'},
    {id: 25, name: 'Rua José Francisco Marques'},
    {id: 26, name: 'Rua Darcio Titoto'},
    {id: 27, name: 'Rua Silvio Titoto'},
    {id: 28, name: 'Rua Francisco Gallante'},
    {id: 29, name: 'Rua João Flávio de Moraes'},
    {id: 30, name: 'Rua Elídio Silva'},
    {id: 31, name: 'Rua Oswaldo Uzuelli'},
    {id: 32, name: 'Rua Geraldo Garcia Barbosa'},
    {id: 33, name: 'Rua Benedito Nunes de Oliveira'},
    {id: 34, name: 'Rua Sebastião da Costa'},
    {id: 35, name: 'Rua Paulo de Souza Nogueira'},
    {id: 36, name: 'Rua Henrique Rastelli'},
    {id: 37, name: 'Rua João Barão Cabrera'},
    {id: 38, name: 'Rua João de Aguiar'},
    {id: 39, name: 'Rua Francisco Britto Morais'},
    {id: 40, name: 'Rua Antônio Marcolino'},
    {id: 41, name: 'Rua Monteiro Filho'},
    {id: 42, name: 'Rua Elígio Baricalla'},
    {id: 43, name: 'Rua Benedito Cunha Mattos'},
    {id: 44, name: 'Rua Francisco Martins Filho'},
    {id: 45, name: 'Rua Sérgio Caressato'},
    {id: 46, name: 'Rua 01'},
    {id: 47, name: 'Rua 02'},
    {id: 48, name: 'Rua 03'},
    {id: 49, name: 'Rua José Carnaval'},
    {id: 50, name: 'Rua Jovenil Vieira dos Santos'},
  ],
  Cravinhos: [
    {id: 1, name: 'Avenida José Bellini'},
    {id: 2, name: 'Rua Afonso Garbelini'},
    {id: 3, name: 'Rua Afonso Zaparolli'},
    {id: 4, name: 'Rua Angelo Batiston'},
    {id: 5, name: 'Rua Antonio de Oliveira júnior'},
    {id: 6, name: 'Rua Antonio J. da Silva'},
    {id: 7, name: 'Rua Antonio Lopes'},
    {id: 8, name: 'Rua Antonio Lopes'},
    {id: 9, name: 'Rua Antonio Pizzi'},
    {id: 10, name: 'Rua Antonio Quaglio'},
    {id: 11, name: 'Rua Carlos Martinelli'},
    {id: 12, name: 'Rua Casemiro Gaspar'},
    {id: 13, name: 'Rua Domingos A. Vieira'},
    {id: 14, name: 'Rua Domingos Perossi'},
    {id: 15, name: 'Rua Manoel A. Nogueira'},
    {id: 16, name: 'Rua Emilio Del Bianco'},
    {id: 17, name: 'Rua Etore Scalabrini'},
    {id: 18, name: 'Rua João Bizuti'},
    {id: 19, name: 'Rua João Bizutti'},
    {id: 20, name: 'Rua Jose Belini'},
    {id: 21, name: 'Rua Jose javali'},
    {id: 22, name: 'Rua Manuel Francisco Loureiro'},
    {id: 23, name: 'Rua Paulo Kanayama'},
    {id: 24, name: 'Rua Pedro Bagatim'},
    {id: 25, name: 'Rua Renato Calegari'},
    {id: 26, name: 'Rua Salim Capez'},
    {id: 27, name: 'Rua Victorio Campioni'},
    {id: 28, name: 'Rua Victorio Molezini'},
    {id: 29, name: 'Rua Adriano Dos Santos'},
    {id: 30, name: 'Rua Antônio Amoroso'},
    {id: 31, name: 'Rua Atílio Battiston'},
    {id: 32, name: 'Rua Domingos Brasca'},
    {id: 33, name: 'Rua Domingos Carloni'},
    {id: 34, name: 'Rua Domingos Rizzo'},
    {id: 35, name: 'Rua Doutor Manoel Arantes Nogueira'},
    {id: 36, name: 'Rua Eduardo Carrascosa'},
    {id: 37, name: 'Rua Emilio Del Bianco'},
    {id: 38, name: 'Rua João Bizutti'},
    {id: 39, name: 'Rua João Moraes'},
    {id: 40, name: 'Rua José Gonçalves de Moraes'},
    {id: 41, name: 'Rua José Marques'},
    {id: 42, name: 'Rua Luiz Santori'},
    {id: 43, name: 'Rua Máximo Glincani'},
    {id: 44, name: 'Rua Namen Jorge'},
    {id: 45, name: 'Rua Salim Salomão'},
    {id: 46, name: 'Rua Wladimir chaves'},
    {id: 47, name: 'Rua Anacleto Lopez Blanez'},
    {id: 48, name: 'Rua Angelo Capecci'},
    {id: 49, name: 'Rua Angelo Mario Perossi'},
    {id: 50, name: 'Rua Antonio Luiz Netto'},
    {id: 51, name: 'Rua Artur José Fraga Silveira'},
    {id: 52, name: 'Rua Deoclécio de Queiroz'},
    {id: 53, name: 'Rua Emílio Ferdinando'},
    {id: 54, name: 'Rua Fernando Rigo Thomazeli'},
    {id: 55, name: 'Rua Geraldo Palmarim'},
    {id: 56, name: 'Rua João Paciulo'},
    {id: 57, name: 'Rua José Bidinhelo'},
    {id: 58, name: 'Rua José Ferdinando'},
    {id: 59, name: 'Rua Lindolpho Mercatelli'},
    {id: 60, name: 'Rua Luis de Lima'},
    {id: 61, name: 'Rua Maria Silva Nogueira'},
    {id: 62, name: 'Rua Mario Benzi'},
    {id: 63, name: 'Rua Matheus Faria'},
    {id: 64, name: 'Rua Natal Rossi'},
    {id: 65, name: 'Rua Orlando Ringer'},
    {id: 66, name: 'Rua Severino Onofre de Mello'},
    {id: 67, name: 'Rua Valdir Sertório Barrosso'},
    {id: 68, name: 'Rua Virginia Zanatto Arjona'},
    {id: 69, name: 'Avenida Alcides Carrascosa'},
    {id: 70, name: 'Rua 2º Sargento José Augusto Ardenche'},
    {id: 71, name: 'Rua António vieira'},
    {id: 72, name: 'Rua Benedicto Floriano'},
    {id: 73, name: 'Rua Breno Capati Trevisam'},
    {id: 74, name: 'Rua Celso da Silva'},
    {id: 75, name: 'Rua Dionisio Maran'},
    {id: 76, name: 'Rua Euclides Ferreira'},
    {id: 77, name: 'Rua Fernando carlos Turazzi'},
    {id: 78, name: 'Rua Gilberto de Camargo Maran'},
    {id: 79, name: 'Rua Helio Sigmarini'},
    {id: 80, name: 'Rua José Faramiglio'},
    {id: 81, name: 'Rua José Sertório'},
    {id: 82, name: 'Rua Luis Roncolato'},
    {id: 83, name: 'Rua Olga Carrascorsa Pavan'},
    {id: 84, name: 'Rua Soldado raimundo xavier'},
    {id: 85, name: 'Rua Valdir Piolli'},
    {id: 86, name: 'Rua Vicente Bertoni Junior'},
  ],
  Years: [
    {id: 1, name: 'Até 12', type: '12'},
    {id: 2, name: 'De 13 à 17', type: '17'},
    {id: 3, name: 'De 18 à 25', type: '25'},
    {id: 4, name: 'De 26 à 40', type: '40'},
    {id: 5, name: 'Acima de 40', type: '41'},
  ],
  NeedOld: [
    {id: 1, name: 'Possui Bíblia', type: 'BI', dbName: 'bible'},
    {id: 2, name: 'Evangélico', type: 'EV', dbName: 'evangelical'},
    {id: 3, name: 'Contato', type: 'CT', dbName: 'contact'},
    {id: 4, name: 'Frequenta Igreja', type: 'FI', dbName: 'frequentsChurch'},
    {id: 5, name: 'Culto no lar', type: 'CL', dbName: 'cultHome'},
    {id: 6, name: 'Estudo Bíblico', type: 'EB', dbName: 'studyBible'},
    {id: 7, name: 'Estudo a Confirmar', type: 'EF', dbName: 'studyConfimation'},
    {id: 8, name: 'Pedido de Oração', type: 'PO', dbName: 'prayerRequest'},
    {id: 9, name: 'Reconciliou', type: 'RC', dbName: 'reconciled'},
    {id: 10, name: 'Visita', type: 'VS', dbName: 'visit'},
    {
      id: 11,
      name: 'Aceita a Cristo (Adulto)',
      type: 'AD',
      dbName: 'acceptChrist',
    },
  ],
  NeedNew: [
    {id: 1, name: 'Possui Bíblia', type: 'BI', dbName: 'bible'},
    {id: 2, name: 'Evangélico', type: 'EV', dbName: 'evangelical'},
    {id: 3, name: 'Contato', type: 'CT', dbName: 'contact'},
    {id: 4, name: 'Frequenta Igreja', type: 'FI', dbName: 'frequentsChurch'},
    {id: 5, name: 'Culto no lar', type: 'CL', dbName: 'cultHome'},
    {id: 6, name: 'Estudo Bíblico', type: 'EB', dbName: 'studyBible'},
    {id: 7, name: 'Estudo a Confirmar', type: 'EF', dbName: 'studyConfimation'},
    {id: 8, name: 'Pedido de Oração', type: 'PO', dbName: 'prayerRequest'},
    {id: 9, name: 'Reconciliou', type: 'RC', dbName: 'reconciled'},
    {id: 10, name: 'Visita', type: 'VS', dbName: 'visit'},
    {
      id: 11,
      name: 'Aceita a Cristo (Criança)',
      type: 'AC',
      dbName: 'acceptChrist',
    },
  ],
  Actions: [
    {id: 1, name: 'Clinico Geral', type: 'CG', dbName: 'medical'},
    {id: 2, name: 'Optomestrista', type: 'OF', dbName: 'optician'},
    {id: 3, name: 'Pressão', type: 'AF', dbName: 'pressure'},
    {id: 4, name: 'Glicose', type: 'GL', dbName: 'glucose'},
    {id: 5, name: 'Estética', type: 'ES', dbName: 'aesthetics'},
    {id: 6, name: 'Corte de Cabelo', type: 'CC', dbName: 'cuttingHair'},
    {id: 7, name: 'Cabelo Penteado', type: 'CP', dbName: 'hairstyle'},
    {id: 8, name: 'Unha', type: 'UN', dbName: 'Nail'},
    {id: 9, name: 'Sombrancelha', type: 'SB', dbName: 'Eyebrow'},
  ],
  Tribe: [
    {id: 1, name: 'Aser'},
    {id: 2, name: 'Benjamim'},
    {id: 3, name: 'Dã'},
    {id: 4, name: 'Efraim'},
    {id: 5, name: 'Gade'},
    {id: 6, name: 'Issacar'},
    {id: 7, name: 'Judá'},
    {id: 8, name: 'Manassés'},
    {id: 9, name: 'Naftali'},
    {id: 10, name: 'Rúben'},
    {id: 11, name: 'Simeão'},
    {id: 12, name: 'Zebulom'},
  ],
};
